language: scala
scala:
- 2.10.4
- 2.11.4
script: sbt clean coverage test
after_success: sbt coveralls
env:
  global:
    secure: D9G18LeDfVsT0bZauY4Ng1OVJDv2YDW1G3T/Rqwo8NNaN0bAPFT2Z2uNjZWRmF+J1KKa/kR1bgHmlZvO1FzZQIHwlDULpyuYlBl+mmeBMDBxNQ3+nbsE14J7jHcBW1LfY0+Iz2T7ZWQTtKW/bbxp6UWvCaWtUCjNEzY8sVwBd7c=
